// Real-statement fixtures (Prompt 8C).
//
// The actual Kuda and PalmPay statement PDFs live under
// tests/fixtures/statements/{Kuda,Palmpay}/ together with the pdfjs
// text-layer snapshots captured from them (`.extracted.json`). The snapshots
// are generated from the PDFs and never hand-edited; the PDFs are the source
// of truth. When a future parser prompt lands, it builds against these
// fixtures — parser tests must never synthesize statements.
//
// Snapshot regeneration: run the same pdfjs extraction the app performs at
// runtime (`rowsFromPdf` in lib/statementImport.ts) and write
// `{ pages: [{ items: [{ str, x, y }] }] }`.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  groupPdfLines,
  groupPdfRows,
  rowsFromPdfPage,
} from "../../../lib/statementImport";

const fixtureDir = path.dirname(fileURLToPath(import.meta.url));

export interface PdfTextItem {
  str: string;
  x: number;
  y: number;
}

export interface ExtractedPage {
  items: PdfTextItem[];
}

/** Which optional normalized fields the REAL statement carries. A parser may
 *  only produce a field listed here — everything else stays absent; missing
 *  values are never forced into fake ones (Prompt 8C). */
export interface FixtureOptionalFields {
  /** Running balance per transaction (as in debit/credit + balance columns). */
  balance: boolean;
  /** Bank transaction reference / transaction id column. */
  reference: boolean;
  /** Counterparty (named recipient / sender inside the narration). */
  counterparty: boolean;
  /** Bank-assigned category / type column. */
  category: boolean;
  /** Account (or sub-account) the statement covers. */
  account: boolean;
  /** Transaction time alongside the date. */
  time: boolean;
  /** A separate value-date column. */
  valueDate: boolean;
}

export interface StatementFixture {
  /** Stable id — the future parser id / `importSource.bank` candidate. */
  id: "kuda" | "kuda-real" | "palmpay" | "gtco-real" | "opay";
  /** Display label. */
  label: string;
  /** Real statement PDF, relative to this file's directory. */
  pdfFile: string;
  /** pdfjs text-layer snapshot, relative to this file's directory. */
  snapshotFile: string;
  /** REAL OCR output of the scanned PDF (generated by scripts/ocr-check.mjs,
   *  never hand-edited) — the ground truth for the OCR path when the PDF has
   *  no text layer (8D/8E). */
  ocrTextFile?: string;
  pages: number;
  /** Whether pdfjs can extract a transaction text layer from the PDF. */
  textLayer: "present" | "absent";
  /** ISO date this fixture's PARSE was last checked against the real file —
   *  not when the file was committed. A fixture can sit in the repo for
   *  months while the bank quietly changes its export; OPay's did, and the
   *  failure only showed up in the live app. Bump this when you re-read the
   *  real file and re-confirm the numbers. */
  lastVerified: string;
  /** What the real file actually proves, in the same verified-vs-
   *  representative tiering the email templates use (docs/15_EMAIL_PARSING.md):
   *
   *  "end-to-end" — a test parses the real extraction and asserts figures
   *      taken from the statement's own printed totals.
   *  "partial"    — a test parses the real extraction, but it covers only
   *      part of the file or only one of the parser's input paths.
   *  "none"       — the file is in the repo but no test reads it; the
   *      parser's tests are representative constructions only. */
  coverage: "end-to-end" | "partial" | "none";
  /** Why `coverage` is what it is — specifically, what is NOT covered. */
  coverageNote: string;
  /** Observed layout facts (from the real PDF, incl. its OCR output). */
  layout: string[];
  optionalFields: FixtureOptionalFields;
}

export const STATEMENT_FIXTURES: readonly StatementFixture[] = [
  {
    id: "kuda",
    label: "Kuda",
    pdfFile: "./Kuda/Customer Statement.pdf",
    snapshotFile: "./Kuda/kuda.extracted.json",
    ocrTextFile: "./Kuda/kuda.ocr.txt",
    pages: 2,
    textLayer: "absent",
    lastVerified: "2026-08-26",
    coverage: "partial",
    coverageNote:
      "OCR path only — the real OCR text is parsed end-to-end, but it reads just 5 transactions because page 2 of the scan is too dark to read, and no real TEXT-LAYER Kuda statement exists in the repo, so that half of the parser is exercised only by representative rows in lib/__tests__/kudaParser.test.ts.",
    layout: [
      "scanned/image pages — no extractable transaction text (2 pages, 6 image XObjects, 3 JPEG streams)",
      "only the page markers 'Page 1 of 2' / 'Page 2 of 2' survive pdfjs text extraction; OCR (scripts/ocr-check.mjs) reads the printed layout (kuda.ocr.txt)",
      "header block: 'Account Number' + 'Date' labels, account number 2003640955, statement period '01/07/2026 - 14/08/2026', address, 'Opening Balance' / 'Closing Balance' labels (44.33 / 69.33)",
      "'Summary' section: 'Type | Opening Balance | Closing Balance' rows per pocket (Spend Account, Spend + Save (1 Pocket))",
      "per-account sections: 'Spend Account' and 'Spend + Save' — 'Money In Money Out Opening Balance Closing Balance' totals row, then the table header 'Date/Time | Money In | Money Out | Category | To/From | Description | Balance' (the Spend + Save table omits the Category column)",
      "transactions print as TWO lines: the date line (dd/mm/yy date, flow amount, category/to/from/description start, running balance) then the time line (hh:mm:ss + wrapped category/description continuation)",
      "amounts with the naira sign (OCR reads it as '#'); the Description column embeds '/'-separated reference-like strings ('Disbursment/3000127755/Kuda sportybet') — narration, not a reference column",
      "page 2 is a dark/noisy scan — OCR reads almost nothing ('Page 2 of 2' only)",
    ],
    optionalFields: {
      balance: true,
      reference: false,
      counterparty: true,
      category: true,
      account: true,
      time: true,
      valueDate: false,
    },
  },
  {
    id: "kuda-real",
    label: "Kuda (rasterized export)",
    pdfFile: "./KUDA-real.pdf",
    snapshotFile: "./KUDA-real.extracted.json",
    ocrTextFile: "./KUDA-real.ocr.txt",
    pages: 2,
    textLayer: "absent",
    lastVerified: "2026-08-26",
    coverage: "partial",
    coverageNote:
      "Same statement as the scanned fixture, rasterized; proves only that pdfjs finds no text layer and that OCR reproduces the same 5 transactions.",
    layout: [
      "rasterized export of the SAME statement as the scanned fixture (account 2003640955, period 01/07/2026 - 14/08/2026): every page is a strip of JPEG images — the raw content stream draws only image XObjects plus the 'Page 1 of 2' / 'Page 2 of 2' text runs",
      "pdfjs text extraction (legacy + modern builds share the engine) surfaces ONLY the two page markers — no fonts beyond the marker font (Type0 CIDFontType2 'MYFGFW+SuisseIntl-Regular', ToUnicode maps just the marker glyphs), no selectable transaction text exists",
      "the transaction table is identical to the scanned fixture: 'Date/Time | Money In | Money Out | Category | To/From | Description | Balance' (OCR reads the printed naira sign as '#')",
      "the Spend + Save pocket has its own Category-less table ('Date/Time | Money In | Money Out | To | Description | Balance')",
      "REAL OCR of this file (scripts/ocr-check.mjs pattern: mupdf render at scale 3 + tesseract.js eng, vendored assets) reproduces the same statement text as kuda.ocr.txt — the parser's 5 known transactions",
      "page 2 is a dark/noisy scan — OCR reads almost nothing ('Page 2 of 2' only)",
    ],
    optionalFields: {
      balance: true,
      reference: false,
      counterparty: true,
      category: true,
      account: true,
      time: true,
      valueDate: false,
    },
  },
  {
    id: "palmpay",
    label: "PalmPay",
    pdfFile: "./Palmpay/Statements download_20260815074349_9e9648a8-2628-4fea-850c-a8a24f29c56e.pdf",
    snapshotFile: "./Palmpay/palmpay.extracted.json",
    pages: 3,
    textLayer: "present",
    lastVerified: "2026-08-26",
    coverage: "end-to-end",
    coverageNote:
      "lib/__tests__/palmpayParser.test.ts parses the real extraction and reconciles against the printed Total Money In / Total Money Out.",
    layout: [
      "account-statement header block: Name, Phone Number, Account Number, Total Money In ₦183,800.71, Statement Period, Total Money Out ₦340,270.00, Print Time, Address",
      "5-column table header: Transaction Date | Transaction Detail | Money In (NGN) | Money Out (NGN) | Transaction ID",
      "transaction rows: 'MM/DD/YYYY HH:MM:SS AM/PM' date; Transaction Detail and Transaction ID may wrap across lines; signed amounts — '+' only in Money In, '−' only in Money Out",
      "page footer page numbers ('1'/'2'/'3'); amounts use thousands commas and 2 decimals",
    ],
    optionalFields: {
      balance: false,
      reference: true,
      counterparty: true,
      category: false,
      account: true,
      time: true,
      valueDate: false,
    },
  },
  {
    id: "gtco-real",
    label: "GTCO (password-protected export)",
    pdfFile: "./GTCO-real-protected.pdf",
    snapshotFile: "./GTCO-real.extracted.json",
    pages: 5,
    textLayer: "present",
    lastVerified: "2026-08-26",
    coverage: "end-to-end",
    coverageNote:
      "statementFixtures.test.ts asserts all 49 real transactions with exact dates, amounts, chained balances and references. Covers the FIRST of the file's three accounts by design; the other two must not be imported.",
    layout: [
      "PASSWORD-PROTECTED (Standard security handler, /V 2 /R 3 /Length 128 = RC4-128): pdfjs opens it with the owner password; without one it throws PasswordException code 1, with a wrong one code 2. The unlock password is user-provided — the committed regression tests read it from the GTCO_STATEMENT_PASSWORD env var and skip cleanly when unset",
      "ONE file, THREE accounts: SAVINGS 066XXXX272 (pages 1-3), GTTARGET 081XXXX044 (page 4) and GTTARGET 079XXXX533 (page 5). Each account prints its own 'Statement Period … Currency' block + 'CUSTOMER STATEMENT' line + 'Trans. Date | Value Date | Reference | Debits | Credits | Balance | Originating Branch | Remarks' table — only the FIRST account's 49 transactions are imported (multi-account statements must not mix accounts)",
      "dates print as '01-Nov-2025' (dd-MMM-yyyy); amounts may lead with a dot ('.20' = 20 kobo); balances chain exactly (21.79 → 21.77 → 80,021.77 → … → 21.77)",
      "the text layer emits NO text for empty cells — every row is SPARSE, so rows are misaligned when read left-packed. Alignment is by the table header's column geometry (rowsFromPdfItems in lib/statementImport.ts, triggered by the 8-token GTCO header): missing cells become explicit empties and long narrations land in the Originating Branch cell ('635 AKIN ADESOLA NIBSS Instant Payment Outward')",
      "long narrations WRAP onto their own lines with no date or amounts ('000013251104113448000524454894 NIP TRANSFER TO' / 'PALMPAY - DAVID OSAHON OGBEIDE'); the columnar engine attaches wrap lines to the NEAREST transaction by page line (rowYs)",
      "pages 2-3 reprint the table header (a section marker, not a transaction); 'Statement Period 01-Nov-2025-30-Nov-2025' label/value rows after page 3 stop the parse so the later accounts are never read",
      "optional fields: running balance ✓, reference ✓ ('GTW'-prefixed refs, transient review aid), counterparty ✓ (inside narrations), value date ✓; no category column, no transaction time",
    ],
    optionalFields: {
      balance: true,
      reference: true,
      counterparty: true,
      category: false,
      account: true,
      time: false,
      valueDate: true,
    },
  },
  {
    id: "opay",
    label: "OPay",
    pdfFile: "./Opay/DAVID OSAHON OGBEIDE_8082389369_20260827085939.pdf",
    snapshotFile: "./Opay/opay.extracted.json",
    pages: 11,
    textLayer: "present",
    lastVerified: "2026-08-27",
    coverage: "end-to-end",
    coverageNote:
      "tests/fixtures/statements/opayReal.test.ts reconciles all 250 transactions against both printed summary blocks. This fixture existed but was wired into NOTHING before 2026-08-27, which is how the format drift reached the live app.",
    // Re-read from the PDF and re-verified 2026-08-27. The earlier entry
    // described a single 150-transaction table and a "repair pass" that no
    // longer exists; both were wrong.
    layout: [
      "ONE file, TWO complete statements, each with its own header block and its own table: Wallet Account 8082389369 (pages 1-7, Total Debit ₦782,090.50 / count 77, Total Credit ₦782,090.50 / count 73) and Savings Account (pages 7-11, Total Debit ₦388,370.50 / count 60, Total Credit ₦388,348.12 / count 40) — 250 transactions in total, and unlike GTCO both belong to the same wallet, so both are imported",
      "8-column table header, printed across TWO baselines: 'Balance After' sits one line above 'Trans. Time | Value Date | Description | Debit (₦) | Credit (₦) | ... | Channel | Transaction Reference'. Aligned by column geometry the currency marker tears apart, so the header cells arrive as 'Balance After ₦)' and '( Channel' — headerToken strips orphaned brackets so both columns still match their role",
      "the SECOND table's money columns sit ~38pt further left than the first's, and its continuation pages reprint no header: column anchors must carry from page to page (rowsFromPdfPage) and re-anchor at the second header, or pages 8-11 collapse the Debit/Credit/Balance triple into one cell",
      "'--' is the empty-money marker — OPay prints it in whichever money column does not apply, on EVERY row. Read as an unparseable amount it rejects the entire statement",
      "one transaction spans a BLOCK of lines with the date/amount line in the MIDDLE: the '|'-separated narration ('Transfer to NAME | Bank | account') and the 24-digit Transaction Reference both wrap onto the lines above AND below it, one line-height (~6pt) apart, with ~21pt between blocks",
      "dates print as '30 Jul 2026 16:08:05' (a combined datetime in Trans. Time) with a separate Value Date; amounts use thousands commas + 2 decimals; Channel is 'Mobile' on every row",
      "OWealth auto-save, withdrawals and 'OWealth Interest Earned' (sub-naira credits) are real money rows; the two tables' opening/closing balances are ₦0.00, so debit and credit totals do NOT net to zero across the file",
    ],
    optionalFields: {
      balance: true,
      reference: true,
      counterparty: true,
      category: false,
      account: true,
      time: true,
      valueDate: true,
    },
  },
];

export function findFixture(id: string): StatementFixture {
  const fixture = STATEMENT_FIXTURES.find((entry) => entry.id === id);
  if (fixture === undefined) {
    throw new Error(`Unknown statement fixture: ${id}`);
  }
  return fixture;
}

/** Absolute path of the real statement PDF. */
export function fixturePdfPath(id: string): string {
  const fixture = findFixture(id);
  return path.join(fixtureDir, fixture.pdfFile);
}

/** Absolute path of the pdfjs text-layer snapshot. */
export function fixtureSnapshotPath(id: string): string {
  const fixture = findFixture(id);
  return path.join(fixtureDir, fixture.snapshotFile);
}

/** The pdfjs text-layer snapshot captured from the real PDF. */
export function loadFixtureSnapshot(id: string): ExtractedPage[] {
  const raw = readFileSync(fixtureSnapshotPath(id), "utf8");
  const parsed = JSON.parse(raw) as { pages: ExtractedPage[] };
  return parsed.pages;
}

/** The REAL OCR output of a scanned fixture (see scripts/ocr-check.mjs) —
 *  the exact text the app's OCR path produced from the PDF. */
export function loadFixtureOcrText(id: string): string {
  const fixture = findFixture(id);
  if (fixture.ocrTextFile === undefined) {
    throw new Error(`No OCR text fixture for: ${id}`);
  }
  return readFileSync(path.join(fixtureDir, fixture.ocrTextFile), "utf8");
}

/** Statement cells exactly as the app would produce them at runtime:
 *  snapshot items → `groupPdfLines`, page by page, in page order. */
export function fixtureCells(id: string): string[][] {
  const pages = loadFixtureSnapshot(id);
  const rows: string[][] = [];
  for (const page of pages) {
    rows.push(...groupPdfLines(page.items));
  }
  return rows;
}

/** One y position per `fixtureCells` row, page by page (each row's line keeps
 *  its pdfjs y). Wrapped-line parsers (PalmPay) consume this as the geometry
 *  that attaches continuation lines to their transaction line (Prompt 8J). */
export function fixtureRowYs(id: string): (number | undefined)[] {
  const pages = loadFixtureSnapshot(id);
  const ys: (number | undefined)[] = [];
  for (const page of pages) {
    ys.push(...groupPdfRows(page.items).map((row) => row.y));
  }
  return ys;
}

/** Statement cells exactly as the runtime PDF path produces them: snapshot
 *  items → `rowsFromPdfItems` (header-anchored column alignment when the
 *  page's table header carries columnar vocabulary), page by page, in page
 *  order. Sparse text layers (GTCO) yield 8-cell rows with explicit empties. */
export function fixtureAlignedCells(id: string): string[][] {
  const pages = loadFixtureSnapshot(id);
  const rows: string[][] = [];
  // Threads table-column anchors across pages exactly as the runtime page
  // loop does. Continuation pages print no header of their own, so without
  // this the fixture path drifts away from the app it is meant to mirror.
  let anchors: number[] | null = null;
  for (const page of pages) {
    const result = rowsFromPdfPage(page.items, anchors);
    anchors = result.anchors;
    rows.push(...result.rows.map((row) => row.cells));
  }
  return rows;
}

/** One y position per `fixtureAlignedCells` row, page by page — the geometry
 *  the columnar engine uses to attach wrapped narration lines to the nearest
 *  transaction (Prompt 8J). */
export function fixtureAlignedRowYs(id: string): (number | undefined)[] {
  const pages = loadFixtureSnapshot(id);
  const ys: (number | undefined)[] = [];
  let anchors: number[] | null = null;
  for (const page of pages) {
    const result = rowsFromPdfPage(page.items, anchors);
    anchors = result.anchors;
    ys.push(...result.rows.map((row) => row.y));
  }
  return ys;
}